spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fenix_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          preferred_uuid_jdbc_type: BINARY

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html